name: CI Pipeline

on:
  push:
    branches:
      - main  # Change to your branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      # Install PowerShell
      - name: Install PowerShell
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https software-properties-common
          wget -q "https://packages.microsoft.com/keys/microsoft.asc" -O- | sudo apt-key add -
          wget -q https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y powershell
      
      # Install Azure PowerShell Module
      - name: Install Azure PowerShell Module
        run: pwsh -Command "Install-Module -Name Az -AllowClobber -Scope CurrentUser -Force"

      # Login to Azure (using Service Principal)
      - name: Login to Azure
        env:
            AZURE_APP_ID: ${{ secrets.AZURE_APP_ID }}
            AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
            AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          pwsh -Command "
            $AppID = $env:AZURE_APP_ID
            $Password = $env:AZURE_PASSWORD
            $Tenant = $env:AZURE_TENANT_ID
            $SecurePassword = ConvertTo-SecureString $Password -AsPlainText -Force
            $Cred = New-Object System.Management.Automation.PSCredential ($AppID, $SecurePassword)
            Connect-AzAccount -Credential $Cred -Tenant $Tenant         
          "

      # Run the PowerShell Script
      - name: Run CreateVM Script
        run: pwsh ./CreateVM.ps1
