name: CI Pipeline

on:
  push:
    branches:
      - main  # Adjust as necessary for your branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      # Install PowerShell
      - name: Install PowerShell
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https software-properties-common
          wget -q "https://packages.microsoft.com/keys/microsoft.asc" -O- | sudo apt-key add -
          wget -q https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y powershell
      
      # Install Azure PowerShell Module
      - name: Install Azure PowerShell Module
        run: pwsh -Command "Install-Module -Name Az -AllowClobber -Scope CurrentUser -Force"

      # Login to Azure (using Service Principal)
      - name: Login to Azure
        env:
            AZURE_APP_ID: ${{ secrets.AZURE_APP_ID }}
            AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
            AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
            ErrorActionPreference: "Stop"
        run: |
          pwsh -Command "
            # Validate variables
            Write-Host 'AppID: $Env:AZURE_APP_ID'
            Write-Host 'TenantId: $Env:AZURE_TENANT_ID'

            # Convert to secure string
            $SecurePassword = ConvertTo-SecureString $Env:AZURE_PASSWORD -AsPlainText -Force
            $Cred = New-Object System.Management.Automation.PSCredential ($Env:AZURE_APP_ID, $SecurePassword)

            # Connect to Azure
            Connect-AzAccount -Credential $Cred -Tenant $Env:AZURE_TENANT_ID
          "

      # Run the PowerShell Script
      - name: Run CreateVM Script
        run: pwsh ./CreateVM.ps1
