name: CI Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Install PowerShell
      - name: Install PowerShell
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https software-properties-common
          wget -q "https://packages.microsoft.com/keys/microsoft.asc" -O- | sudo apt-key add -
          wget -q https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y powershell

      # Step 3: Install Pester for testing
      - name: Install Pester
        run: pwsh -Command "Install-Module -Name Pester -Force -SkipPublisherCheck"

      # Step 4: Run Pester Tests
      - name: Run Pester Tests
        run: pwsh -Command "Invoke-Pester -Script './Tests/script.tests.ps1' -Output Detailed"
