name: CI Pipeline

on:
  push:
    branches:
      - main  # Change to your branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Script
          run: ./CreateVM.ps1
          shell: pwsh

